/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ittp.pbo.view;

import javax.swing.*;
import java.util.Date;
import java.sql.Connection;

import com.ittp.pbo.entity.Kendaraan;
import com.ittp.pbo.entity.Mobil;
import com.ittp.pbo.entity.Motor;
import com.ittp.pbo.entity.Parkir;
import com.ittp.pbo.entity.ParkirDetail;
import com.ittp.pbo.service.ParkirService;
import com.ittp.pbo.connection.DatabaseUtilities;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MHIKAM
 */
public class EntryForm extends javax.swing.JFrame {
    
    public static String noPlatGlobal;
    private ParkirService parkirService;
    public static String noPlat;
    /**
     * Creates new form EntryForm
     */
    public EntryForm() {
        initComponents();
        Connection connection = DatabaseUtilities.getMyConnection();
        parkirService = new ParkirService(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfNoPlat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfMerek = new javax.swing.JTextField();
        cbJenisKendaraan = new javax.swing.JComboBox<>();
        tfWarna = new javax.swing.JTextField();
        jdcWaktuMasuk = new com.toedter.calendar.JDateChooser();
        btnSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(138, 173, 138));

        jLabel2.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel2.setText("No Plat");

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Kendaraan");

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel4.setText("Merek");

        btnKembali.setBackground(new java.awt.Color(209, 190, 154));
        btnKembali.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel5.setText("Waktu Masuk");

        tfNoPlat.setBackground(new java.awt.Color(209, 190, 154));
        tfNoPlat.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        tfNoPlat.setForeground(new java.awt.Color(30, 30, 30));

        jLabel6.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel6.setText("Warna");

        tfNama.setBackground(new java.awt.Color(209, 190, 154));
        tfNama.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        tfNama.setForeground(new java.awt.Color(30, 30, 30));

        tfMerek.setBackground(new java.awt.Color(209, 190, 154));
        tfMerek.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        tfMerek.setForeground(new java.awt.Color(30, 30, 30));
        tfMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMerekActionPerformed(evt);
            }
        });

        cbJenisKendaraan.setBackground(new java.awt.Color(209, 190, 154));
        cbJenisKendaraan.setEditable(true);
        cbJenisKendaraan.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        cbJenisKendaraan.setForeground(new java.awt.Color(30, 30, 30));
        cbJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor", "Mobil" }));

        tfWarna.setBackground(new java.awt.Color(209, 190, 154));
        tfWarna.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        tfWarna.setForeground(new java.awt.Color(30, 30, 30));
        tfWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWarnaActionPerformed(evt);
            }
        });

        jdcWaktuMasuk.setBackground(new java.awt.Color(209, 190, 154));
        jdcWaktuMasuk.setForeground(new java.awt.Color(30, 30, 30));
        jdcWaktuMasuk.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N

        btnSimpan.setBackground(new java.awt.Color(209, 190, 154));
        btnSimpan.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel1.setText("Nama");

        jLabel7.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("MASUKKAN KENDARAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKembali))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNama)
                                    .addComponent(tfMerek)
                                    .addComponent(cbJenisKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfWarna)
                                    .addComponent(jdcWaktuMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcWaktuMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnSimpan)
                .addGap(47, 47, 47)
                .addComponent(btnKembali)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ISOMETRIC CAR PARKING (1).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        MainForm mainform = new MainForm();
        mainform.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tfMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMerekActionPerformed

    private void tfWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWarnaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        noPlat = tfNoPlat.getText();
        String nama = tfNama.getText();
        String jenisKendaraan = (String) cbJenisKendaraan.getSelectedItem();
        String merek = tfMerek.getText();
        String warna = tfWarna.getText();
        Date waktuMasuk = (Date) jdcWaktuMasuk.getDate();
        
        Kendaraan kendaraan;
        if (jenisKendaraan.equals("Motor")) {
            kendaraan = new Motor(noPlat, nama, merek, warna);
        } else {
            kendaraan = new Mobil(noPlat, nama, merek, warna);
        }
        kendaraan.setJenisKendaraan(jenisKendaraan);
        String kodeParkir = parkirService.generateKodeParkir();
        Parkir parkir = new Parkir(parkirService.generateKodeParkir(), waktuMasuk, null);

        ParkirDetail parkirDetail = new ParkirDetail(parkir, kendaraan);
        
        parkirService.MasukanKendaraan(parkirDetail);
        
        JOptionPane.showMessageDialog(this, "Karcis Parkir\n"
            + "---------------------------\n"
            + "Kode Parkir: " + kodeParkir + "\n"
            + "No Plat: " + noPlat + "\n"
            + "Jenis Kendaraan: " + jenisKendaraan + "\n"
            + "Waktu Masuk: " + waktuMasuk);
        Document document = new Document();
        try {
            String filePath = "C:\\Users\\MHIKAM\\OneDrive\\Dokumen\\!ITTP\\Semester 4\\PBO\\AplikasiParkir\\AplikasiLoketParkir-v4\\Karcis\\" + kodeParkir + ".pdf";
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            document.add(new Paragraph("Karcis Parkir"));
            document.add(new Paragraph("---------------------------"));
            document.add(new Paragraph("Kode Parkir: " + kodeParkir));
            document.add(new Paragraph("No Plat: " + noPlat));
            document.add(new Paragraph("Jenis Kendaraan: " + jenisKendaraan));
            document.add(new Paragraph("Waktu Masuk: " + waktuMasuk));
            document.close();
            JOptionPane.showMessageDialog(this, "Karcis Parkir berhasil disimpan sebagai PDF!");

        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saat menyimpan karcis parkir sebagai PDF!");
        }
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenisKendaraan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcWaktuMasuk;
    private javax.swing.JTextField tfMerek;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoPlat;
    private javax.swing.JTextField tfWarna;
    // End of variables declaration//GEN-END:variables
}
