/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ittp.pbo.view;

import javax.swing.JOptionPane;

import com.ittp.pbo.service.ParkirService;
import com.ittp.pbo.view.*;
import com.ittp.pbo.connection.DatabaseUtilities;
import java.io.FileNotFoundException;
import java.util.Date;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MHIKAM
 */
public class ExitForm extends javax.swing.JFrame {
    
    private Connection connection;
    private ParkirService parkirService;
    /**
     * Creates new form ExitForm
     */
    public ExitForm() {
        initComponents();
        connection = DatabaseUtilities.getMyConnection();
        parkirService = new ParkirService(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfKodeParkir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcWaktuKeluar = new com.toedter.calendar.JDateChooser();
        btnKeluarkan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aa (1)_2.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(147, 165, 193));

        tfKodeParkir.setBackground(new java.awt.Color(209, 190, 154));
        tfKodeParkir.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        tfKodeParkir.setForeground(new java.awt.Color(30, 30, 30));
        tfKodeParkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeParkirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Kode Parkir");

        jLabel2.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Waktu Keluar");

        jdcWaktuKeluar.setBackground(new java.awt.Color(209, 190, 154));
        jdcWaktuKeluar.setForeground(new java.awt.Color(30, 30, 30));
        jdcWaktuKeluar.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N

        btnKeluarkan.setBackground(new java.awt.Color(209, 190, 154));
        btnKeluarkan.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        btnKeluarkan.setForeground(new java.awt.Color(30, 30, 30));
        btnKeluarkan.setText("Keluarkan");
        btnKeluarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarkanActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(209, 190, 154));
        btnKembali.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(30, 30, 30));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKembali))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfKodeParkir)
                            .addComponent(jdcWaktuKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnKeluarkan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKodeParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addComponent(jdcWaktuKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btnKeluarkan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        MainForm mainform = new MainForm();
        mainform.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tfKodeParkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeParkirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodeParkirActionPerformed

    private void btnKeluarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarkanActionPerformed
        // TODO add your handling code here:
        String kodeParkir = tfKodeParkir.getText();
        Date waktuKeluar = (Date) jdcWaktuKeluar.getDate();
        
        if (kodeParkir.isEmpty() || waktuKeluar == null) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
            return;
        }
        ParkirService parkirService = new ParkirService(connection);
        boolean isUpdated = false;
        try {
            isUpdated = parkirService.KeluarkanKendaraan(kodeParkir, waktuKeluar);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ExitForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (isUpdated) {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal diupdate!");
        }
    }//GEN-LAST:event_btnKeluarkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluarkan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcWaktuKeluar;
    private javax.swing.JTextField tfKodeParkir;
    // End of variables declaration//GEN-END:variables
}
